### ISSUE TITLE
License

### ISSUE THREAD

**Issue by funwithtriangles** [spite/FaceMeshFaceGeometry#1]
Loving what you've done here! Just wondering what the license is for this project? I'd love to use some parts of the code in another non-commercial open source project I'm working on.

**Comment by spite** [comment]
I always forget the license. Just added it, MIT. 

The triangulation data comes from https://github.com/tensorflow/tfjs-models/blob/master/facemesh/demo/triangulation.js, which has an Apache license... i'm not sure how that works, then

**Comment by funwithtriangles** [comment]
Thanks! I don't really have a good knowledge of licenses but I'm assuming the Apache license is relatively compatible with MIT.  🤷‍♂️
