### ISSUE TITLE
normalizeCoords: true doesn't seem to do anything

### ISSUE THREAD

**Issue by jmartinezuk** [spite/FaceMeshFaceGeometry#4]
I'm trying to use just the mesh, but have it static, just moving the face expressions, ignoring the position and rotation, and I'm having no luck. This setting should at least prevent the mesh from growing and shrinking. Or am I going in the wrong direction. Do you have any tips on achieving the above? Many thanks for the THREE helper by the way.

**Comment by spite** [comment]
It's all combined in the model´s result, you can't have expression without the face movement.

`normalizeCoords` is useful for something like https://spite.github.io/FaceMeshFaceGeometry/examples/instanced/index.html where you can place the face anywhere, but it will still be moving. You might need a library different from FaceMesh to get the results you want.

**Comment by jmartinezuk** [comment]
Gotcha. I thought of a way, attaching camera and lights to the be tracked from the face mesh position. I'll see how it goes.
