### ISSUE TITLE
Demos not loading

### ISSUE THREAD

**Issue by zz85** [spite/FaceMeshFaceGeometry#5]
Demos links like https://spite.github.io/FaceMeshFaceGeometry/examples/mask/index.html seem no longer work because the tfhub site hosting the model json seems to no longer be around https://tfhub.dev/tensorflow/tfjs-model/blazeface/1/default/1/model.json?tfjs-format=file seems

**Comment by spite** [comment]
Are you sure? it seems to be working here...

**Comment by zz85** [comment]
hmm, you're right https://updownradar.com/status/tfhub.dev

maybe it's broken or blocked from my ISP 😢
