### ISSUE TITLE
Is there a way to safely pause/stop the video stream?

### ISSUE THREAD

**Issue by lindy-dev** [spite/FaceMeshFaceGeometry#8]
Great work on this repo btw. I wanted to know if there is any way to pause or stop the video input stream in the "mask" example? Do let me know if I can help to make it possible.

**Comment by spite** [comment]
Your app can control the video element and the animation loop, so it should be possible to either pause the video or add a flag to skip the model prediction.

**Comment by lindy-dev** [comment]
Great, I will look into that! Thank you so much for your help in this!
