### ISSUE TITLE
Mobile phone compatibility

### ISSUE THREAD

**Issue by ByJuanCho98** [spite/FaceMeshFaceGeometry#9]
Does this works on mobile?

**Comment by spite** [comment]
Have you tried before asking? 

It should work, as long as the device supports WebGL, has a camera, and is powerful enough to run TensorFlow.js.

**Comment by ByJuanCho98** [comment]
Yes, the demo works in mobile. In my project I Add some 3d objects with three.js and works fine in desktop but not in mobile. I think the problem might be where I host the page.

**Comment by ByJuanCho98** [comment]
Hey @spite have u implemented occluders ? IDK where to begin.
